app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import FloatField, SubmitField, StringField
from wtforms.validators import DataRequired


class ThresholdForm(FlaskForm):
    threshold = FloatField('Treshold', validators=[DataRequired()])
    submit = SubmitField('Speichern')


class InteractionForm(FlaskForm):
    shortcut = StringField('Shortcut', validators=[DataRequired()])
    submit = SubmitField('Speichern')

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, template_folder='templates')

from app.main import routes

app/main/routes.py
from flask import render_template, flash, redirect, url_for, request, current_app, jsonify
from flask_login import current_user, login_required
from app import db
from app.main import bp
from app.main.forms import ThresholdForm, InteractionForm
from app.models import InteractionShortcut, Session, SessionInteractionShortcut, SessionDevice
from app.devices import *


def get_session_info():
    active_session_id = current_user.get_active_session_id()
    if active_session_id:
        return '<span>Sitzung aktiv <a class="btn btn-primary btn-sm ml-2" href="{}">Sitzung beenden</a>'\
            .format(url_for('main.stop_new_session'))
    else:
        return 'Keine Sitzung aktiv <a class="btn btn-primary btn-sm ml-2" href="{}">Neue Sitzung</a>'\
            .format(url_for('main.select_interactions'))


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    return render_template('index.html', title='Home', heading='Hallo ' + current_user.name,
                           session_info=get_session_info())


@bp.route('/threshold', methods=['GET', 'POST'])
@login_required
def threshold():
    form = ThresholdForm(threshold=current_user.threshold)
    if form.validate_on_submit():
        user = current_user
        user.threshold = form.threshold.data
        db.session.add(user)
        db.session.commit()
        flash('Neuer Schwellenwert gespeichert.')
    return render_template('threshold.html', title='Home', heading='Einstellen des Kinetose-Schwellenwerts',
                           session_info=get_session_info(), form=form)


@bp.route('/shortcuts', methods=['GET', 'POST'])
@login_required
def shortcuts():
    form = InteractionForm()
    interaction_shortcuts = InteractionShortcut.query.filter_by(id_user=current_user.id)
    if form.validate_on_submit():
        interaction_shortcut = InteractionShortcut(id_user=current_user.id, shortcut=form.shortcut.data)
        db.session.add(interaction_shortcut)
        db.session.commit()
        flash('Neuer Shortcut gespeichert.')
        return redirect(url_for('main.shortcuts'))
    return render_template('interactions.html', title='Home', heading='Verwalten der Interaktions-Shortcuts',
                           session_info=get_session_info(), form=form, interaction_shortcuts=interaction_shortcuts)


@bp.route('/shortcuts/delete/<id>', methods=['GET', 'POST'])
@login_required
def shortcut_delete(id):
    interaction_shortcut = InteractionShortcut.query.filter_by(id=id, id_user=current_user.id).first_or_404()
    db.session.delete(interaction_shortcut)
    db.session.commit()
    flash('Shortcut gelöscht.')
    return redirect(url_for('main.shortcuts'))


@bp.route('/websession/start', methods=['GET', 'POST'])
@login_required
def start_new_session():
    devices = request.form.getlist('device_checkbox')
    if len(devices) < 1:
        flash('Bitte mindestens ein Gerät wählen!')
        return redirect(url_for('main.select_devices'), code=307)
    interaction_ids = request.form.getlist('interaction_checkbox')
    if len(interaction_ids) < 1:
        flash('Bitte mindestens einen Interaktions-Shortcut wählen!')
        return redirect(url_for('main.select_interactions'))
    new_session = Session(id_user=current_user.id)
    db.session.add(new_session)
    db.session.commit()
    for device in devices:
        new_session_device = SessionDevice(id_session=current_user.get_active_session_id(), device=device)
        db.session.add(new_session_device)
        db.session.commit()
    for interaction_id in interaction_ids:
        new_session_interaction_shortcut = SessionInteractionShortcut(id_session=current_user.get_active_session_id(),
                                                                      id_interaction_shortcut=interaction_id)
        db.session.add(new_session_interaction_shortcut)
        db.session.commit()
    return redirect(url_for('main.index'))


@bp.route('/websession/stop', methods=['GET', 'POST'])
@login_required
def stop_new_session():
    active_session_id = current_user.get_active_session_id()
    if active_session_id:
        session = Session.query.filter_by(id=active_session_id, id_user=current_user.id).first_or_404()
        session.end()
        db.session.commit()
    return redirect(url_for('main.index'))


@bp.route('/websession/new/interactions', methods=['GET', 'POST'])
@login_required
def select_interactions():
    if current_user.get_active_session_id():
        flash('Es ist bereits eine Sitzung aktiv.')
        return redirect(url_for('main.index'))
    interaction_shortcuts = InteractionShortcut.query.filter_by(id_user=current_user.id)
    return render_template('interaction_selection.html', title='Home',
                           heading='Bitte die Interaktions-Shortcuts der Sitzung wählen', session_info='Neue Sitzung',
                           interaction_shortcuts=interaction_shortcuts)


@bp.route('/websession/new/devices', methods=['GET', 'POST'])
@login_required
def select_devices():
    interaction_ids = request.form.getlist('interaction_checkbox')
    if len(interaction_ids) < 1:
        flash('Bitte mindestens einen Interaktions-Shortcut wählen!')
        return redirect(url_for('main.select_interactions'))
    return render_template('device_selection.html', title='Home', devices=deviceClasses,
                           heading='Bitte die Geräte der Sitzung wählen', session_info='Neue Sitzung',
                           interactions=interaction_ids)


@bp.route('/websession/prvalue', methods=['GET'])
@login_required
def get_web_session_pr_value():
    users_active_session = current_user.get_active_session()
    pr = users_active_session.current_pr_value
    return render_template('blank.html', title='Home', content=pr)

app/main/templates/_footer.html
    <!-- Footer -->
    <footer class="sticky-footer bg-white">
        {% include '__footercontent.html' %}
    </footer>
    <!-- End of Footer -->

app/main/templates/_interaction_lister.html
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Interaktion #{{ i }}</h6>
    </div>
    <div class="card-body px-0 pt-0">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xl-8 col-lg-6"><p><div class="text-primary font-weight-bold">Shortcut</div>{{ interaction_shortcut.shortcut }}</p></div>
                <div class="col-xl-4 col-lg-6">
                    <a href=" {{ url_for('main.shortcut_delete', id=interaction_shortcut.id) }}" class="mt-4 btn btn-danger btn-icon-split float-xl-right float-sm-left">
                        <span class="icon text-white-50">
                            <i class="fas fa-trash"></i>
                        </span>
                        <span class="text">Löschen</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

app/main/templates/_pr_chart.html
<script type="text/javascript">
    Chart.defaults.global.defaultFontFamily = 'Nunito', '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
    Chart.defaults.global.defaultFontColor = '#858796';

    var prArr = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

    // https://bantel.informatik.hs-aalen.de/download/ibs/programme/ajax.js
    function AJAX(method, url, data, async) {
        var _http = null;
        if (window.XMLHttpRequest) {
            _http = new XMLHttpRequest();
        } else if (window.ActiveXObject) {
            _http = new ActiveXObject("Microsoft.XMLHTTP");
        } else
            alert("Kein AJAX möglich!");

        if (_http != null) {
            _http.open(method, url, async);
            _http.send(data);
            _http.onreadystatechange = function() {
                if (this.readyState == 4 && this.status == 200) {
                    prArr.shift();
                    prArr.push(this.responseText);
                    myLineChart.update();
                }
            }
        }
        return _http;
    }

    // https://stackoverflow.com/a/12830454
    function number_format(num, scale) {
      if(!("" + num).includes("e")) {
        return +(Math.round(num + "e+" + scale)  + "e-" + scale);
      } else {
        var arr = ("" + num).split("e");
        var sig = ""
        if(+arr[1] + scale > 0) {
          sig = "+";
        }
        return +(Math.round(+arr[0] + "e" + sig + (+arr[1] + scale)) + "e-" + scale);
      }
    }

    var ctx = document.getElementById("prChart");
    var myLineChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: ['vor 20 Sek.', 'vor 19 Sek.', 'vor 18 Sek.', 'vor 17 Sek.', 'vor 16 Sek.', 'vor 15 Sek.', 'vor 14 Sek.', 'vor 13 Sek.', 'vor 12 Sek.', 'vor 11 Sek.', 'vor 10 Sek.', 'vor 9 Sek.', 'vor 8 Sek.', 'vor 7 Sek.', 'vor 6 Sek.', 'vor 5 Sek.', 'vor 4 Sek.', 'vor 3 Sek.', 'vor 2 Sek.', 'vor 1 Sek.', 'vor 0 Sek.'],
        datasets: [{
          label: "Wahrscheinlichkeit",
          lineTension: 0.3,
          backgroundColor: "rgba(78, 115, 223, 0.05)",
          borderColor: "rgba(78, 115, 223, 1)",
          pointRadius: 3,
          pointBackgroundColor: "rgba(78, 115, 223, 1)",
          pointBorderColor: "rgba(78, 115, 223, 1)",
          pointHoverRadius: 3,
          pointHoverBackgroundColor: "rgba(78, 115, 223, 1)",
          pointHoverBorderColor: "rgba(78, 115, 223, 1)",
          pointHitRadius: 10,
          pointBorderWidth: 2,
          data: prArr,
        }],
      },
      options: {
        maintainAspectRatio: false,
        layout: {
          padding: {
            left: 10,
            right: 25,
            top: 25,
            bottom: 0
          }
        },
        scales: {
          xAxes: [{
            time: {
              unit: 'second'
            },
            gridLines: {
              display: false,
              drawBorder: false
            },
            ticks: {
              maxTicksLimit: 20
            }
          }],
          yAxes: [{
            ticks: {
              beginAtZero: true,
              maxTicksLimit: 10,
              padding: 10,
              callback: function(value, index, values) {
                return number_format(value, 3);
              }
            },
            gridLines: {
              color: "rgb(234, 236, 244)",
              zeroLineColor: "rgb(234, 236, 244)",
              drawBorder: false,
              borderDash: [2],
              zeroLineBorderDash: [2]
            }
          }],
        },
        legend: {
          display: false
        },
        tooltips: {
          backgroundColor: "rgb(255,255,255)",
          bodyFontColor: "#858796",
          titleMarginBottom: 10,
          titleFontColor: '#6e707e',
          titleFontSize: 14,
          borderColor: '#dddfeb',
          borderWidth: 1,
          xPadding: 15,
          yPadding: 15,
          displayColors: false,
          intersect: false,
          mode: 'index',
          caretPadding: 10,
          callbacks: {
            label: function(tooltipItem, chart) {
              var datasetLabel = chart.datasets[tooltipItem.datasetIndex].label || '';
              return datasetLabel + ': ' + number_format(tooltipItem.yLabel, 3);
            }
          }
        }
      }
    });

    setInterval(function () {
        AJAX('GET', '/websession/prvalue', null, true);
    }, 1000);
</script>

app/main/templates/base.html
<!DOCTYPE html>
<html lang="de">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Samuel Blickle">

    {% if title %}
    <title>{{ title }} - Kinetosis Detector</title>
    {% else %}
    <title>Willkommen beim Kinetosis Detector</title>
    {% endif %}

    <!-- Custom fonts for this template-->
    <link href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{{ url_for('static', filename='css/sb-admin-2.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/custom.css') }}" rel="stylesheet">


</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url_for('main.index') }}">
            <div class="sidebar-brand-icon">
                <i class="fas fa-gamepad"></i>
            </div>
                <div class="sidebar-brand-text mx-3">Kinetosis Detector</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.index') }}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Übersicht</span></a>
        </li>

        <!-- Nav Item - Add -->
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.select_interactions') }}">
                <i class="fas fa-fw fa-plus"></i>
                <span>Neue Sitzung</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading">
            Einstellungen
        </div>

        <!-- Nav Item - Complete -->
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.threshold') }}">
                <i class="fas fa-fw fa-chart-line"></i>
                <span>Kinetose Schwellenwert</span>
            </a>

        <!-- Nav Item - Incomplete -->
        <li class="nav-item">
            <a class="nav-link" href="{{  url_for('main.shortcuts') }}">
                <i class="fas fa-fw fa-keyboard"></i>
                <span>Interaktionsmöglichkeiten</span>
            </a>

        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-block">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow-sm">

                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>

                <!-- Session Status -->
                <div class="h5 font-weight-bold ml-2 mt-2">{{ session_info|safe }}</div>

                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">

                    <!-- Nav Item - User Information -->
                    <li class="nav-item dropdown no-arrow">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ current_user.name }}</span>
                            <img class="img-profile rounded-circle" src="{{ current_user.avatar(60) }}">
                        </a>
                        <!-- Dropdown - User Information -->
                        <div class="dropdown-menu dropdown-menu-right shadow-sm animated--grow-in" aria-labelledby="userDropdown">
<!--                            <a class="dropdown-item" href="#">
                                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                Profile
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                Settings
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                Activity Log
                            </a>
                            <div class="dropdown-divider"></div>-->
                            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                Abmelden
                            </a>
                        </div>
                    </li>

                </ul>

            </nav>
            <!-- End of Topbar -->

            <!-- Begin Page Content -->
            <div class="container-fluid">

                {% block content %}{% endblock %}

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        {% include '_footer.html' %}
    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Wirklich abmelden?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Um dich auszuloggen klicke bitte unten auf "Abmelden".</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Abbrechen</button>
                <a class="btn btn-primary" href="{{ url_for('auth.logout') }}">Abmelden</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

<!-- Core plugin JavaScript-->
<script src="{{ url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>

<!-- Custom scripts for all pages-->
<script src="{{ url_for('static', filename='js/sb-admin-2.min.js') }}"></script>

<script src="{{ url_for('static', filename='vendor/chart.js/Chart.js') }}"></script>
{% include '_pr_chart.html' %}

{% block scripts %}{% endblock %}

</body>

</html>

app/main/templates/blank.html
{{ content }}

app/main/templates/device_selection.html
{% extends "base.html" %}

{% block content %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h4 mb-0 text-gray-800">{{ heading }}</h1>
    </div>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
           <div class="small">
                {% for message in messages %}
                <p style="color: #e74a3b">{{ message }}</p>
                {% endfor %}
           </div>
        {% endif %}
    {% endwith %}
    <form action="{{ url_for('main.start_new_session') }}" method="post">
        {% for device in devices %}
            <input class="h4 text-lg" type="checkbox" name="device_checkbox" value="{{ device }}"><span> {{ device }}</span><br>
        {% endfor %}
        {% for interaction in interactions %}
            <input type="hidden" name="interaction_checkbox" value="{{ interaction }}">
        {% endfor %}
        <input type="submit" class="btn btn-primary btn-user mt-4" value="Weiter">
    </form>
{% endblock %}

app/main/templates/index.html
{% extends "base.html" %}

{% block content %}
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h4 mb-0 text-gray-800">{{ heading }}</h1>
        </div>

        {% with messages = get_flashed_messages() %}
                {% if messages %}
                   <div class="small">
                        {% for message in messages %}
                        <p style="color: #e74a3b">{{ message }}</p>
                        {% endfor %}
                   </div>
                {% endif %}
        {% endwith %}

        <div class="container-fluid px-0">
            <div class="row">
                <div class="col-12">
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Kinetose-Wahrscheinlichkeit</h6>
                        </div>
                        <div class="card-body px-0 pt-0">
                            <canvas id="prChart" class="chartjs-render-monitor" style="display: block;" height="400"></canvas>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

app/main/templates/interaction_selection.html
{% extends "base.html" %}

{% block content %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h4 mb-0 text-gray-800">{{ heading }}</h1>
    </div>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
           <div class="small">
                {% for message in messages %}
                <p style="color: #e74a3b">{{ message }}</p>
                {% endfor %}
           </div>
        {% endif %}
    {% endwith %}
    {% if interaction_shortcuts.count() > 0 %}
    <form action="{{ url_for('main.select_devices') }}" method="post">
        {% for interaction_shortcut in interaction_shortcuts %}
            {% set i = loop.index %}
            <input class="h4 text-lg" type="checkbox" name="interaction_checkbox" value="{{ interaction_shortcut.id }}"><span> Interaktion #{{ i }}: <span class="font-weight-bold text-gray-800">{{ interaction_shortcut.shortcut }}</span></span><br>
        {% endfor %}
        <input type="submit" class="btn btn-primary btn-user mt-4" value="Weiter">
    </form>
    {% else %}
        <h5>Es sind noch keine Interaktionsmöglichkeiten hinterlegt. Bitte zuerst eine <a href="{{ url_for('main.shortcuts') }}">Interaktionsmöglichkeit definieren</a>.</h5>
    {% endif %}
{% endblock %}

app/main/templates/interactions.html
{% extends "base.html" %}

{% block content %}

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h4 mb-0 text-gray-800">{{ heading }}</h1>
    </div>

    <div class="container-fluid px-0">
        <div class="row">
            {% for interaction_shortcut in interaction_shortcuts %}
                {% set i = loop.index %}
                <div class="col-6 col-offset-2">
                    {% include '_interaction_lister.html' %}
                </div>
            {% endfor %}
        </div>
    </div>

    <div>
        <form action="" method="post" novalidate>
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.shortcut(size=64, class="form-control", placeholder="Neuer Shortcut") }}
                {% for error in form.shortcut.errors %}
                     <div class="text-center small">
                         <p style="color: #e74a3b;">{{ error }}</p>
                     </div>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary btn-user btn-block") }}
            </div>
        </form>
    </div>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
           <div class="text-center small">
                {% for message in messages %}
                <p style="color: #1cc88a">{{ message }}</p>
                {% endfor %}
           </div>
        {% endif %}
    {% endwith %}

{% endblock %}

app/main/templates/threshold.html
{% extends "base.html" %}

{% block content %}
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h4 mb-0 text-gray-800">{{ heading }}</h1>
        </div>
        <div>
            <form action="" method="post" novalidate>
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.threshold(size=64, class="form-control", placeholder="Schwellenwert") }}
                    {% for error in form.threshold.errors %}
                         <div class="text-center small">
                             <p style="color: #e74a3b;">{{ error }}</p>
                         </div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    {{ form.submit(class="btn btn-primary btn-user btn-block") }}
                </div>
            </form>
        </div>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
               <div class="text-center small">
                    {% for message in messages %}
                    <p style="color: #1cc88a">{{ message }}</p>
                    {% endfor %}
               </div>
            {% endif %}
        {% endwith %}
{% endblock %}